sudo: required
dist: trusty

language:
    cpp

compiler:
    - clang # 3.5.0
    - gcc # 4.8.4

install:
    # Install dependencies
    - sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x
    - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
    - sudo apt-get update -qq
    - sudo apt-get install -qy cmake qt55base libgdal1-dev libfreenect-dev libvxl1-dev
    # CC submodules
    - git submodule init && git submodule update

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release
      -DQT5_ROOT_PATH=/opt/qt55
      -DOPTION_USE_DXF_LIB=ON
      -DOPTION_USE_SHAPE_LIB=ON
      -DINSTALL_QANIMATION_PLUGIN=ON
      -DINSTALL_QBLUR_PLUGIN=ON
      -DINSTALL_QDUMMY_PLUGIN=ON
      -DINSTALL_QEDL_PLUGIN=ON
      -DINSTALL_QFACETS_PLUGIN=ON
      -DINSTALL_QHPR_PLUGIN=ON
      -DINSTALL_QPOISSON_RECON_PLUGIN=ON
      -DINSTALL_QSRA_PLUGIN=ON
      -DINSTALL_QSSAO_PLUGIN=ON
      -DINSTALL_QGMMREG_PLUGIN=ON
      -DINSTALL_QPCV_PLUGIN=ON ..

      # -DOPTION_USE_GDAL=ON
      # -DINSTALL_QKINECT_PLUGIN=ON
      # -DLIBFREENECT_INCLUDE_DIR="/usr/include"
      # -DLIBFREENECT_LIBRARY_FILE="/usr/lib/x86_64-linux-gnu/libfreenect.so"

      # For now:
      # - qRansacSD fails on Clang
      # - no libav/FFMPEG. Version in repos is < 10.7 (no frame.h)
      # - could not use CGAL from Ubuntu (< 4.3)

script:
    # We use only 4 core because gcc and clang can be memory hungry
    - make -j2
